### ISSUE TITLE
When using Die as a skilling animation, the animation cannot be cancelled

### ISSUE THREAD

**Issue by Hydrox6** [ArtimosPenguidor/animation-transmog#1]
The animation stops the player from visually moving, and no other animation seems to cancel the player being on the floor. It also doesn't cancel the animation when turning off the plugin.

I'm not sure if this also happens for other replacement options (combat, teleport, movement)

**Comment by ArtimosPenguidor** [comment]
That is very interesting, I didn't test that exact config:animation combo. I wonder if it's because the "die" animation is traditionally used with removing or transporting the player back to spawn. The animation may not have a set "end frame", or at least that's my speculation.

I could possible end the animation manually after the "dying" motion finishes.

Thanks for the input, I'll take a look and hopefully have a fix for it soon.

**Comment by ArtimosPenguidor** [comment]
I can confirm, this bug seems to happen only with the Die animation, and only when you try to cancel the action playing the animation. Maybe I can just make it so that if you attempt to walk (aka cancel the action and animation) it manually sets the animation to -1?

**Comment by ArtimosPenguidor** [comment]
I may actually just remove the Die animation from everything except the teleport config, as I don't want to possibly cause any weird behavior from trying to manually cancel the Die animation.
