### ISSUE TITLE
Teleport Animation conflicting with Tombs of Amascut's crystal scarabs

### ISSUE THREAD

**Issue by Enriath** [ArtimosPenguidor/animation-transmog#11]
When activating a crystal scarab, I guess the plugin thinks you're using a teletab as both use the same animation. This results in the chosen teleport animation playing (in my case Darkness Ascends), the player disappearing, and the camera being locked to the position it was before activating the item. The player can still move around and do stuff, but it's incredibly disorienting.

**Comment by ArtimosPenguidor** [comment]
Wow, well that's no good! Thanks for letting me know, I will take a look at it here soon to try and differentiate between the crystal scarabs and teleporting.

**Comment by ArtimosPenguidor** [comment]
This issue should be resolved with the latest update https://github.com/ArtimosPenguidor/animation-transmog/commit/d3bd75aea96ff18c6947a4c19452724dfa3085d8

This essentially disables the plugin in certain regions, like ToA. It's the only good way to go about this since the crystal scarab uses the same exact animation as a teletab and the plugin can't distinguish the two.

I'll close the issue once the new update has been released in Runelite.

Thanks!
Nick
