### ISSUE TITLE
Teleport transmogs are not long enough

### ISSUE THREAD

**Issue by Khufuhk** [ArtimosPenguidor/animation-transmog#12]
Animations for teleport transmogs end before the teleport happens leaving the player in regular standing position for one tick. Would it be possible to delay the beginning to make the animation seamless?

**Comment by ArtimosPenguidor** [comment]
Yeah I've tried addressing this a couple times. It's a bit tricky since there are multiple ways to teleport and each method has different lengths of animations that I'm overriding.

Which teleporting method are you seeing this in? A teletab? A teleport spell? Jewelry?

I'll see if I can refine the way it overrides the normal animations and stretch the custom animations to the amount of frames of the original animation.

**Comment by Khufuhk** [comment]
I noticed with the default spellbook teleports and the amulet of glory, so the purple sphere animation. I actually don't think I tested with it with tabs.

**Comment by ArtimosPenguidor** [comment]
Okay cool I'll take a look and see if I can refine it a bit better. 

Thanks for pointing it out!

I'll let you know on this issue if/when I'm able to fix it.

**Comment by ArtimosPenguidor** [comment]
This issue will be resolved with commit dbf9507c3d3e82a663cdb57a2ba60f6b13abcb6a

**Comment by ArtimosPenguidor** [comment]
Issue will be closed with PR https://github.com/runelite/plugin-hub/pull/4244

**Comment by ArtimosPenguidor** [comment]
This issue should be resolved now. Let me know if you have any more problems. 

Thanks,
Nick
