### ISSUE TITLE
Plank death animation only lasting 1 tic

### ISSUE THREAD

**Issue by SoloDarkness** [ArtimosPenguidor/animation-transmog#13]
My charcter lands on the ground and instantly stands back up with the red bar long before i go to my respawn point. I have seen this plugin working fine on pk streams but cant seem to get it to work for me. Might be user error..?

**Comment by ArtimosPenguidor** [comment]
I don't think this is a user error because I've seen this issue inconsistently. 

It's a bit hard overriding the death animation because the default animations doesn't have a set length and I think it just resets when you respawn. 

I can look into fixing this issue.

**Comment by SoloDarkness** [comment]
thank you! very quick response!

**Comment by ArtimosPenguidor** [comment]
Yup no problem. I'm gonna try to look at this and a couple more issues in a couple days. 

I'll update this issue with what I find.

**Comment by ArtimosPenguidor** [comment]
I figured out what the issue most likely is. The timer I use to count the frames of an animation to know when to end the custom animation doesn't take into account your client FPS.

So I'm assuming your death animation ends so quickly because you probably have uncapped FPS turned on and its really really high haha.

So I'll modify the timer I use to account for FPS (rookie mistake) and that should fix the issue.

**Comment by ArtimosPenguidor** [comment]
I'll try and get this update pushed to the Runelite Plugin Hub in the next day or so. I'll update here when it's done.

**Comment by ArtimosPenguidor** [comment]
Issue will be closed with PR https://github.com/runelite/plugin-hub/pull/4244

**Comment by ArtimosPenguidor** [comment]
This should be fixed now. Let me know if you have any issues. 

Thanks again for bringing this up, it turned out to be the biggest bug in the plugin causing a lot of other issues. The plugin should be running a lot better now. 

Nick
